### ISSUE TITLE
EmbeddedGPT (Feel Free to add)

### ISSUE THREAD

**Issue by mdabir1203** [taranjeet/awesome-gpts#18]
I made this embedded gpt for Embedded system Programmers. The author name is somebody else as I had to borrow my friends GPT-4 :D 

Feel free to test it out. 

How to Use it ? 

- Upload your embedded hardware 
- And then ask questions

Link: https://chat.openai.com/g/g-M5UY1ByFj-embeddedgpt

Demo:

https://github.com/taranjeet/awesome-gpts/assets/66947064/b8df78f1-e929-4a9c-961d-3fa33744b832

 

If you're interested in making this more featured version feel free to reach out to me.

**Comment by aryankhanna475** [comment]
Addressed in PR #25

**Comment by mdabir1203** [comment]
@taranjeet  Can you please change the name by whom it was created. I used my Friends GPT-4

**Comment by mdabir1203** [comment]
The name would be : Mohammad Abir Abbas only
