### ISSUE TITLE
Please Add: OpenStorytelling Plus 

### ISSUE THREAD

**Issue by BryanHarrisScripts** [taranjeet/awesome-gpts#28]
Hi! 

Can you add GPT: Pull request has been sent... 

https://chat.openai.com/g/g-LppT0lwkB-openstorytelling-plus

Thank you. 
Bryan

@BryanHarrisScripts (Github)
@BryanRebooted (X, Youtube)
OpenStorytelling.com (Github Pages)

**Comment by aryankhanna475** [comment]
Resolved in your PR, so closing this.
