### ISSUE TITLE
Please add: RentSavvy

### ISSUE THREAD

**Issue by Theatrix2020** [taranjeet/awesome-gpts#38]
RentSavvy: Your search guide for safe city and neighborhood rentals, offering personalized insights and recommendations.
[https://chat.openai.com/g/g-dNAvmbSZa-rentsavvy](url)

**Comment by aryankhanna475** [comment]
Added

**Comment by Theatrix2020** [comment]
Thank you. Appreciate it,  I think the category for this suits well in 'Real Estate' / Travel  -
