### ISSUE TITLE
Please add: MacroMeter

### ISSUE THREAD

**Issue by jyothishjohnson** [taranjeet/awesome-gpts#41]
Track your daily nutrients intake with MacroMeter.

Track 
 - Carbs
 - Protein
 - Fat
 - Calorie

https://chat.openai.com/g/g-CWeZC6BVi-macrometer-gpt

- Text it or upload photo of your meal, MacroMeter will track your daily intake. 
- Visualise with charts

<img width="431" alt="Screenshot 2023-11-14 at 8 54 51 PM" src="https://github.com/taranjeet/awesome-gpts/assets/29103453/64812661-d678-4408-9ba3-687675a5401b">

PR link: https://github.com/taranjeet/awesome-gpts/pull/40

**Comment by aryankhanna475** [comment]
thanks the PR is merged
