### ISSUE TITLE
GPTs to add

### ISSUE THREAD

**Issue by noname2312** [taranjeet/awesome-gpts#46]
SEO BlogGPT: https://chat.openai.com/g/g-CqSxj3cSa-seo-bloggpt
PEC - Practice English Conversation: https://chat.openai.com/g/g-kowOn5g3r-pec-practice-english-conversation
Professional Rewrite Assistant: https://chat.openai.com/g/g-ZryriIvWZ-professional-rewrite-assistant
My GPT Counselor: https://chat.openai.com/g/g-A2PybUxIf-my-gpt-counselor
YT Shorts Expert: https://chat.openai.com/g/g-wc6rx2PRi-yt-shorts-expert

**Comment by aryankhanna475** [comment]
Added

**Comment by aryankhanna475** [comment]
Added
