### ISSUE TITLE
New GPTs to add

### ISSUE THREAD

**Issue by HeyitsRadinn** [taranjeet/awesome-gpts#47]
🎧 DJGPT

- I'm DJGPT, your go-to AI for all things DJing and music mixing, here to guide you through the exciting world of beats and tracks!
- [Chat now](https://chat.openai.com/g/g-NlwIQ4CSj-djgpt.)
- Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

🎥EditGPT

- Your go-to buddy for all things related to video editing and creating custom images for your projects.
- [Chat now](https://chat.openai.com/g/g-ZhPbXQIr5-editgpt)
- Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

🎧 Audiophile Assistant

- Specializes in providing expert advice on high-fidelity audio, from equipment selection to sound quality analysis.
- [Chat now](https://chat.openai.com/g/g-VbJvVjilC-audiophile-assistant)
- Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

💡 ProductGPT

- A specialized AI assistant designed to generate creative and appealing product names and descriptions, focusing on tech products, eco-friendly items, and fashion.
- [Chat now](https://chat.openai.com/g/g-GUjYfiBrG-productgpt)
- Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

🎧 AbletonGPT

- I'm AbletonGPT, your go-to source for practical tips and troubleshooting advice on Ableton Live 11, dedicated to helping both beginners and intermediate users with their music production queries.
- [Chat now](https://chat.openai.com/g/g-BpSexw4ll-abletongpt)
- Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

🖥️ PC Builder GPT

- I'm PC Builder GPT, your tech-savvy virtual friend who offers expert and approachable advice on building PCs, complete with up-to-date pricing.
- [Chat now](https://chat.openai.com/g/g-gh7PDdmmd-pc-builder-gpt)
- Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

🧳Voyage Guide GPT

- Your virtual travel buddy here to help make your travel planning experience smooth, fun, and informative.
- [Chat now](https://chat.openai.com/g/g-MDExvbFqe-voyage-guide)
- Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

💺Seat Seeker GPT

- Seat Seeker excels in efficiently assisting users to find public seating with specific amenities, using their approximate location.
- [Chat now](https://chat.openai.com/g/g-3AQM5NfzA-seat-seeker)
- Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

**Comment by aryankhanna475** [comment]
Resolved all of them have been added
