### ISSUE TITLE
Seabiscuit: Press Prep - Business GPT

### ISSUE THREAD

**Issue by tomfrazier** [taranjeet/awesome-gpts#52]
[Seabiscuit: Press Prep](https://chat.openai.com/g/g-JSGp95kFT-seabiscuit-press-prep): Be Newsworthy Not A Footnote by [Seabiscuit.ai](https://seabiscuit.ai) 

Get a comprehensive and professional press kit for your business, enhancing your media outreach and public relations efforts.

Category: Business

**Comment by aryankhanna475** [comment]
Added
