### ISSUE TITLE
Please add: Personal carbon guide 

### ISSUE THREAD

**Issue by Theatrix2020** [taranjeet/awesome-gpts#60]
Carbon-footprint count guide: A carbon specialist aiding in analyzing and reducing carbon footprints. [A carbon specialist aiding in analyzing and reducing carbon footprints.](url)

**Comment by aryankhanna475** [comment]
Can you send the proper link, not able to access this link @Theatrix2020

**Comment by Theatrix2020** [comment]
[https://chat.openai.com/g/g-269eJfz9f-carbon-count-guide](url)

**Comment by aryankhanna475** [comment]
Added
