### ISSUE TITLE
please add - interior gpt

### ISSUE THREAD

**Issue by sallumandya1995** [taranjeet/awesome-gpts#65]
InteriorGPT: Transform Your Space with AI 🤖. Discover innovative interior and exterior design concepts, detailed floor plans, and personalized reimaginations of your environment, all powered by Generative AI tech. Elevate your space with a touch of generative design 🏠🎨📸

link - https://chat.openai.com/g/g-MMsjdW9vb-interiorgpt

**Comment by aryankhanna475** [comment]
Added
